### ISSUE TITLE
Block spam hashtags from the bot.

### ISSUE THREAD

**Issue by ChemiKhazi** [Andrelhu/MakeGoodGames-TwitterBot#1]
The bot is retweeting spammy tweets that use the #mplusrewards hashtag, I've noticed at least two other instances of this. This is just the latest one. https://twitter.com/broadway_pat/status/852260200740507648

**Comment by ChemiKhazi** [comment]
Another spam hashtag the bot is inadvertently promoting, #cheats https://twitter.com/dellaalexandri3/status/852098886663520256

**Comment by Andrelhu** [comment]
Thank you so much! I just committed a small fix to skip these undesired hashtags.
